services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-s3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge
